#pragma once

#include <shaderc/shaderc.hpp>
#include <spirv_cross/spirv_cross.hpp>
#include <vulkan/vulkan.hpp>
#include "enums/enum_cast.h"
#include "enums/enum_flags.h"
#include <vector>

namespace lcf {
    using SpvCode = std::vector<uint32_t>;

    enum class ShaderTypeFlagBits : uint8_t 
    {
        eVertex = 1,
        eTessControl = 1 << 1,
        eTessEvaluation = 1 << 2,
        eGeometry = 1 << 3,
        eFragment = 1 << 4,
        eCompute = 1 << 5,
        eAllGraphics = eVertex | eTessControl | eTessEvaluation | eGeometry | eFragment,
        eAll = eAllGraphics | eCompute,
    };
    template <> struct is_enum_flags<ShaderTypeFlagBits> : std::true_type {};

    LCF_MAKE_ENUM_CATEGORY((ShaderTypeFlagBits, vk::ShaderStageFlagBits, shaderc_shader_kind),
        { ShaderTypeFlagBits::eVertex, vk::ShaderStageFlagBits::eVertex, shaderc_vertex_shader },
        { ShaderTypeFlagBits::eTessControl, vk::ShaderStageFlagBits::eTessellationControl, shaderc_tess_control_shader },
        { ShaderTypeFlagBits::eTessEvaluation, vk::ShaderStageFlagBits::eTessellationEvaluation, shaderc_tess_evaluation_shader },
        { ShaderTypeFlagBits::eGeometry, vk::ShaderStageFlagBits::eGeometry, shaderc_geometry_shader },
        { ShaderTypeFlagBits::eFragment, vk::ShaderStageFlagBits::eFragment, shaderc_fragment_shader },
        { ShaderTypeFlagBits::eCompute, vk::ShaderStageFlagBits::eCompute, shaderc_compute_shader },
    );

    enum class ShaderDataType
    {
        Unknown,
		Void,
		Boolean,
        BooleanVec2,
        BooleanVec3,
        BooleanVec4,
		SByte,
        SByteVec2,
        SByteVec3,
        SByteVec4,
		UByte,
        UByteVec2,
        UByteVec3,
        UByteVec4,
		Short,
        ShortVec2,
        ShortVec3,
        ShortVec4,
		UShort,
        UShortVec2,
        UShortVec3,
        UShortVec4,
		Int,
        IntVec2,
        IntVec3,
        IntVec4,
		UInt,
        UIntVec2,
        UIntVec3,
        UIntVec4,
		Int64,
        Int64Vec2,
        Int64Vec3,
        Int64Vec4,
		UInt64,
        UInt64Vec2,
        UInt64Vec3,
        UInt64Vec4,
		AtomicCounter,
		Half,
        HalfVec2,
        HalfVec3,
        HalfVec4,
		Float,
        FloatVec2,
        FloatVec3,
        FloatVec4,
		Double,
        DoubleVec2,
        DoubleVec3,
        DoubleVec4,
		Struct,
		Image,
		SampledImage,
		Sampler,
		AccelerationStructure,
		RayQuery,
		ControlPointArray,
		Interpolant,
		Char
    };

    LCF_MAKE_ENUM_CATEGORY((ShaderDataType, spirv_cross::SPIRType::BaseType, vk::Format),
        { ShaderDataType::Unknown, spirv_cross::SPIRType::Unknown, vk::Format::eUndefined },
        { ShaderDataType::Void, spirv_cross::SPIRType::Void, vk::Format::eUndefined },
        { ShaderDataType::Boolean, spirv_cross::SPIRType::Boolean, vk::Format::eR8Unorm },
        { ShaderDataType::BooleanVec2, spirv_cross::SPIRType::Boolean, vk::Format::eR8G8Unorm },
        { ShaderDataType::BooleanVec3, spirv_cross::SPIRType::Boolean, vk::Format::eR8G8B8Unorm },
        { ShaderDataType::BooleanVec4, spirv_cross::SPIRType::Boolean, vk::Format::eR8G8B8A8Unorm },
        { ShaderDataType::SByte, spirv_cross::SPIRType::SByte, vk::Format::eR8Snorm },
        { ShaderDataType::SByteVec2, spirv_cross::SPIRType::SByte, vk::Format::eR8G8Snorm },
        { ShaderDataType::SByteVec3, spirv_cross::SPIRType::SByte, vk::Format::eR8G8B8Snorm },
        { ShaderDataType::SByteVec4, spirv_cross::SPIRType::SByte, vk::Format::eR8G8B8A8Snorm },
        { ShaderDataType::UByte, spirv_cross::SPIRType::UByte, vk::Format::eR8Uint },
        { ShaderDataType::UByteVec2, spirv_cross::SPIRType::UByte, vk::Format::eR8G8Uint },
        { ShaderDataType::UByteVec3, spirv_cross::SPIRType::UByte, vk::Format::eR8G8B8Uint },
        { ShaderDataType::UByteVec4, spirv_cross::SPIRType::UByte, vk::Format::eR8G8B8A8Uint },
        { ShaderDataType::Short, spirv_cross::SPIRType::Short, vk::Format::eR16Snorm },
        { ShaderDataType::ShortVec2, spirv_cross::SPIRType::Short, vk::Format::eR16G16Snorm },
        { ShaderDataType::ShortVec3, spirv_cross::SPIRType::Short, vk::Format::eR16G16B16Snorm },
        { ShaderDataType::ShortVec4, spirv_cross::SPIRType::Short, vk::Format::eR16G16B16A16Snorm },
        { ShaderDataType::UShort, spirv_cross::SPIRType::UShort, vk::Format::eR16Uint },
        { ShaderDataType::UShortVec2, spirv_cross::SPIRType::UShort, vk::Format::eR16G16Uint },
        { ShaderDataType::UShortVec3, spirv_cross::SPIRType::UShort, vk::Format::eR16G16B16Uint },
        { ShaderDataType::UShortVec4, spirv_cross::SPIRType::UShort, vk::Format::eR16G16B16A16Uint },
        { ShaderDataType::Int, spirv_cross::SPIRType::Int, vk::Format::eR32Sint },
        { ShaderDataType::IntVec2, spirv_cross::SPIRType::Int, vk::Format::eR32G32Sint },
        { ShaderDataType::IntVec3, spirv_cross::SPIRType::Int, vk::Format::eR32G32B32Sint },
        { ShaderDataType::IntVec4, spirv_cross::SPIRType::Int, vk::Format::eR32G32B32A32Sint },
        { ShaderDataType::UInt, spirv_cross::SPIRType::UInt, vk::Format::eR32Uint },
        { ShaderDataType::UIntVec2, spirv_cross::SPIRType::UInt, vk::Format::eR32G32Uint },
        { ShaderDataType::UIntVec3, spirv_cross::SPIRType::UInt, vk::Format::eR32G32B32Uint },
        { ShaderDataType::UIntVec4, spirv_cross::SPIRType::UInt, vk::Format::eR32G32B32A32Uint },
        { ShaderDataType::Int64, spirv_cross::SPIRType::Int64, vk::Format::eR64Sint },
        { ShaderDataType::Int64Vec2, spirv_cross::SPIRType::Int64, vk::Format::eR64G64Sint },
        { ShaderDataType::Int64Vec3, spirv_cross::SPIRType::Int64, vk::Format::eR64G64B64Sint },
        { ShaderDataType::Int64Vec4, spirv_cross::SPIRType::Int64, vk::Format::eR64G64B64A64Sint },
        { ShaderDataType::UInt64, spirv_cross::SPIRType::UInt64, vk::Format::eR64Uint },
        { ShaderDataType::UInt64Vec2, spirv_cross::SPIRType::UInt64, vk::Format::eR64G64Uint },
        { ShaderDataType::UInt64Vec3, spirv_cross::SPIRType::UInt64, vk::Format::eR64G64B64Uint },
        { ShaderDataType::UInt64Vec4, spirv_cross::SPIRType::UInt64, vk::Format::eR64G64B64A64Uint },
        { ShaderDataType::AtomicCounter, spirv_cross::SPIRType::AtomicCounter, vk::Format::eUndefined },
        { ShaderDataType::Half, spirv_cross::SPIRType::Half, vk::Format::eR16Sfloat },
        { ShaderDataType::HalfVec2, spirv_cross::SPIRType::Half, vk::Format::eR16G16Sfloat },
        { ShaderDataType::HalfVec3, spirv_cross::SPIRType::Half, vk::Format::eR16G16B16Sfloat },
        { ShaderDataType::HalfVec4, spirv_cross::SPIRType::Half, vk::Format::eR16G16B16A16Sfloat },
        { ShaderDataType::Float, spirv_cross::SPIRType::Float, vk::Format::eR32Sfloat },
        { ShaderDataType::FloatVec2, spirv_cross::SPIRType::Float, vk::Format::eR32G32Sfloat },
        { ShaderDataType::FloatVec3, spirv_cross::SPIRType::Float, vk::Format::eR32G32B32Sfloat },
        { ShaderDataType::FloatVec4, spirv_cross::SPIRType::Float, vk::Format::eR32G32B32A32Sfloat },
        { ShaderDataType::Double, spirv_cross::SPIRType::Double, vk::Format::eR64Sfloat },
        { ShaderDataType::DoubleVec2, spirv_cross::SPIRType::Double, vk::Format::eR64G64Sfloat },
        { ShaderDataType::DoubleVec3, spirv_cross::SPIRType::Double, vk::Format::eR64G64B64Sfloat },
        { ShaderDataType::DoubleVec4, spirv_cross::SPIRType::Double, vk::Format::eR64G64B64A64Sfloat },
        { ShaderDataType::Struct, spirv_cross::SPIRType::Struct, vk::Format::eUndefined },
        { ShaderDataType::Image, spirv_cross::SPIRType::Image, vk::Format::eUndefined },
        { ShaderDataType::SampledImage, spirv_cross::SPIRType::SampledImage, vk::Format::eUndefined },
        { ShaderDataType::Sampler, spirv_cross::SPIRType::Sampler, vk::Format::eUndefined },
        { ShaderDataType::AccelerationStructure, spirv_cross::SPIRType::AccelerationStructure, vk::Format::eUndefined },
        { ShaderDataType::RayQuery, spirv_cross::SPIRType::RayQuery, vk::Format::eUndefined },
        { ShaderDataType::ControlPointArray, spirv_cross::SPIRType::ControlPointArray, vk::Format::eUndefined },
        { ShaderDataType::Interpolant, spirv_cross::SPIRType::Interpolant, vk::Format::eUndefined },
        { ShaderDataType::Char, spirv_cross::SPIRType::Char, vk::Format::eR8Snorm }
    );

    enum class ShaderResourceType
    {
        Sampler,
        CombinedImageSampler,
        SampledImage,
        StorageImage,
        UniformTexelBuffer,
        StorageTexelBuffer,
        UniformBuffer,
        StorageBuffer,
        PushConstant,
    };
}